apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy81
  labels:
    app: autodeploy81
  namespace: namespace-workflow-1711468137919
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy81
  template:
    metadata:
      labels:
        app: autodeploy81
    spec:
      containers:
        - name: autodeploy81
          image: acrworkflow1711468137919.azurecr.io/image-workflow-1711468137919:latest
          ports:
            - containerPort: 5000